### ISSUE TITLE
“Save Complete Page” missing from firefox extension

### ISSUE THREAD

**Issue by sunjam** [tagspaces/browser-extensions#3]
_Save Complete Page_ is missing from the firefox Tagspaces web clipper.  Can confirm it still works fine on Chrome.

**Comment by uggrock** [comment]
Saving in MHTML format is unfortunately not possible in Firefox, that is the reason for hiding the "Save Complete Page" in Firefox extension.

**Comment by sunjam** [comment]
How do I properly clip pages and formatting without it? Save as Editable is missing a lot of data.
![9d925951-477a-4700-87aa-4aae9f489345](https://user-images.githubusercontent.com/1787238/36396707-5442df34-1574-11e8-95c9-dfdfe597cf3b.png)

**Comment by uggrock** [comment]
This is the best what we can do for the moment. Saving as MHTML was never possible with the Firefox extension. Save as editable is just not saving the css, the whole HTML is actually included and the important content is mostly in the HTML....

Send me the link to the page above in order to debug the extension and see if it really strips something.

**Comment by sunjam** [comment]
Thanks for the info.  Apologies for delayed response.

[Here is the problematic page url](https://help.nextcloud.com/t/evernote-replacement/25004)

Also, [here is another nice GPL licensed Firefox/Chrome extension *Save Page WE* that might interest you.](https://addons.mozilla.org/en-US/firefox/addon/save-page-we/)
[Evernote Replacement - feature _ app ideas - Nextcloud community (1).html.zip](https://github.com/tagspaces/browser-extensions/files/1917353/Evernote.Replacement.-.feature._.app.ideas.-.Nextcloud.community.1.html.zip)
