### ISSUE TITLE
AGPL license?

### ISSUE THREAD

**Issue by laurent22** [tagspaces/browser-extensions#5]
I'm curious, the current license means that the project cannot be used in other open source projects that use a more permissive license such as MIT. In particular, I'm considering using it for [Joplin](https://github.com/laurent22/joplin), which is licensed under MIT, but then I probably cannot.

So I'm wondering, is the license definitely set in stone, or is there any chance it could be changed to something more permissive? Obviously I'd be glad to contribute back any change I make regardless of the license.

**Comment by uggrock** [comment]
The license is fix for now. If you plan to create a browser extension for Joplin, then you can put it in a separate repository and if you use TagSpaces Web Clipper as basis you have to distribute it under AGPL license. Since the web clipper is a completely different software from your main application, the AGPL license should not be an issue for you, even if they communicate in some way.

**Comment by laurent22** [comment]
Thanks for your reply. Keeping the web clipper separate could indeed be an option so I'll look into it.
